/**
 * Pi Agent SDK Integration (PRIMARY)
 * Integration with @mariozechner/pi-agent-core
 * This is the PRIMARY integration for Pi Builder
 */

import type { CodeGenerationRequest } from '../types'

export interface PiAgentSDKConfig {
  sessionId?: string
  steeringMode?: 'all' | 'one-at-a-time'
  followUpMode?: 'all' | 'one-at-a-time'
  maxRetryDelayMs?: number
  getApiKey?: (provider: string) => Promise<string | undefined> | string | undefined
  thinkingBudgets?: Record<string, unknown>
}

export interface AgentTask {
  id: string
  prompt: string
  context?: Record<string, unknown>
  language?: string
  framework?: string
  state?: Record<string, unknown>
}

export interface AgentTaskResult {
  taskId: string
  code: string
  language: string
  explanation: string
  state: Record<string, unknown>
  metadata: {
    tokensUsed: number
    completedAt: Date
    model: string
    sessionId?: string
  }
}

/**
 * Pi Agent SDK Integration
 * PRIMARY integration for Pi Builder
 * Uses the actual @mariozechner/pi-agent-core structure
 */
export class PiAgentSDKIntegration {
  private sessionId?: string
  private steeringMode: 'all' | 'one-at-a-time'
  private followUpMode: 'all' | 'one-at-a-time'
  private tasks: Map<string, AgentTask> = new Map()
  private agentState: Record<string, unknown> = {}

  constructor(config?: PiAgentSDKConfig) {
    this.sessionId = config?.sessionId
    this.steeringMode = config?.steeringMode || 'one-at-a-time'
    this.followUpMode = config?.followUpMode || 'one-at-a-time'
    // Acknowledge config options for potential future use
    void config?.maxRetryDelayMs
    void config?.getApiKey
    void config?.thinkingBudgets
  }

  /**
   * Execute a task using the Pi Agent SDK
   * PRIMARY method for code generation
   */
  async executeTask(request: CodeGenerationRequest): Promise<AgentTaskResult> {
    try {
      const taskId = `task_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`

      console.log(`🤖 Pi Agent executing task: ${taskId}`)
      console.log(`   Prompt: ${request.prompt.substring(0, 50)}...`)
      console.log(`   Language: ${request.language || 'typescript'}`)
      console.log(`   Framework: ${request.framework || 'none'}`)

      const task: AgentTask = {
        id: taskId,
        prompt: request.prompt,
        context: request.context,
        language: request.language || 'typescript',
        framework: request.framework,
        state: { ...this.agentState },
      }

      this.tasks.set(taskId, task)

      // Execute the task through agent loop
      const result = await this.executeAgentLoop(task)

      // Update agent state
      this.agentState = result.state

      console.log(`✅ Agent task completed: ${taskId}`)

      return {
        taskId,
        code: result.code,
        language: result.language,
        explanation: result.explanation,
        state: result.state,
        metadata: {
          tokensUsed: result.tokensUsed,
          completedAt: new Date(),
          model: 'pi-agent-core',
          sessionId: this.sessionId,
        },
      }
    } catch (error) {
      console.error(
        `❌ Agent task failed: ${error instanceof Error ? error.message : String(error)}`
      )
      throw error
    }
  }

  /**
   * Simulate the agent loop
   * In production, this would use actual @mariozechner/pi-agent-core
   */
  private async executeAgentLoop(task: AgentTask): Promise<{
    code: string
    language: string
    explanation: string
    state: Record<string, unknown>
    tokensUsed: number
  }> {
    // Simulate agent loop processing
    console.log(`⚙️ Running agent loop with mode: ${this.steeringMode}/${this.followUpMode}`)

    // Simulate LLM call through agent
    const code = `// Generated by Pi Agent SDK
// Session: ${this.sessionId || 'default'}
// Steering: ${this.steeringMode}
// FollowUp: ${this.followUpMode}
// Prompt: ${task.prompt}
// Language: ${task.language}
// Framework: ${task.framework || 'none'}

${this.generateCodeTemplate(task.language || 'typescript', task.framework)}`

    return {
      code,
      language: task.language || 'typescript',
      explanation: 'Generated by Pi Agent SDK core loop',
      state: { ...task.state, lastTaskId: task.id, completedAt: new Date().toISOString() },
      tokensUsed: Math.ceil((task.prompt.length + code.length) / 4),
    }
  }

  /**
   * Stream task execution for real-time updates
   */
  async *streamTask(request: CodeGenerationRequest): AsyncGenerator<string, AgentTaskResult> {
    const taskId = `task_${Date.now()}_stream`
    console.log(`🔄 Starting stream for task: ${taskId}`)

    yield `Starting agent task...\n`

    // Simulate streaming execution
    const chunks = [
      `Thinking about prompt: "${request.prompt}"\n`,
      `Language: ${request.language || 'typescript'}\n`,
      `Framework: ${request.framework || 'none'}\n`,
      `Generating code...\n`,
      `\`\`\`\n${this.generateCodeTemplate(request.language, request.framework)}\n\`\`\`\n`,
    ]

    for (const chunk of chunks) {
      yield chunk
      await new Promise(resolve => setTimeout(resolve, 100))
    }

    // Return final result
    const code = this.generateCodeTemplate(request.language, request.framework)
    return {
      taskId,
      code,
      language: request.language || 'typescript',
      explanation: 'Streamed from Pi Agent SDK',
      state: { streamed: true },
      metadata: {
        tokensUsed: (code.length / 4),
        completedAt: new Date(),
        model: 'pi-agent-core-stream',
        sessionId: this.sessionId,
      },
    }
  }

  /**
   * Get task status
   */
  getTaskStatus(taskId: string): AgentTask | undefined {
    return this.tasks.get(taskId)
  }

  /**
   * List all tasks
   */
  listTasks(): AgentTask[] {
    return Array.from(this.tasks.values())
  }

  /**
   * Update session ID (for session-based caching)
   */
  setSessionId(sessionId: string): void {
    this.sessionId = sessionId
    console.log(`📋 Session ID updated: ${sessionId}`)
  }

  /**
   * Get current session ID
   */
  getSessionId(): string | undefined {
    return this.sessionId
  }

  /**
   * Update agent state
   */
  setAgentState(state: Record<string, unknown>): void {
    this.agentState = { ...this.agentState, ...state }
  }

  /**
   * Get agent state
   */
  getAgentState(): Record<string, unknown> {
    return { ...this.agentState }
  }

  /**
   * Clear task history
   */
  clearTasks(): void {
    this.tasks.clear()
    console.log('🗑️ Task history cleared')
  }

  private generateCodeTemplate(language?: string, framework?: string): string {
    const lang = language || 'typescript'
    const fw = framework || 'vanilla'

    if (lang === 'typescript') {
      if (fw === 'react') {
        return `import React from 'react'

export const Component: React.FC = () => {
  return <div>Generated by Pi Agent</div>
}`
      }
      return `export async function generatedFunction(input: string): Promise<string> {
  console.log('Generated by Pi Agent SDK:', input)
  return \`Processed: \${input}\`
}`
    }

    if (lang === 'javascript') {
      return `async function generatedFunction(input) {
  console.log('Generated by Pi Agent SDK:', input)
  return \`Processed: \${input}\`
}

export { generatedFunction }`
    }

    if (lang === 'python') {
      return `async def generated_function(input_str: str) -> str:
    """Generated by Pi Agent SDK"""
    print(f"Generated by Pi Agent SDK: {input_str}")
    return f"Processed: {input_str}"
`
    }

    return `# Generated by Pi Agent SDK\necho "Hello from Pi Agent"`
  }
}
